---
# Handlers can be used to restart the services if required.
- name: Restart Kafka
  ansible.builtin.systemd:
    name: kafka
    state: restarted

- name: Restart Zookeeper
  ansible.builtin.systemd:
    name: zookeeper
    state: restarted
